const chats = [
  {
    id: 1,
    primary: "Brunch this week?",
    secondary:
      "I'll be in the neighbourhood this week. Let's grab a bite to eat",
    person: "/static/images/avatar/5.jpg",
  },
  {
    id: 2,
    primary: "Birthday Gift",
    secondary: `Do you have a suggestion for a good present for John on his work
        anniversary. I am really confused & would love your thoughts on it.`,
    person: "/static/images/avatar/1.jpg",
  },
  {
    id: 3,
    primary: "Recipe to try",
    secondary:
      "I am try out this new BBQ recipe, I think this might be amazing",
    person: "/static/images/avatar/2.jpg",
  },
  {
    id: 4,
    primary: "Yes!",
    secondary: "I have the tickets to the ReactConf for this year.",
    person: "/static/images/avatar/3.jpg",
  },
  {
    id: 5,
    primary: "Doctor's Appointment",
    secondary:
      "My appointment for the doctor was rescheduled for next Saturday.",
    person: "/static/images/avatar/4.jpg",
  },
  {
    id: 6,
    primary: "Discussion",
    secondary: `Menus that are generated by the bottom app bar (such as a bottom
        navigation drawer or overflow menu) open as bottom sheets at a higher elevation
        than the bar.`,
    person: "/static/images/avatar/5.jpg",
  },
  {
    id: 7,
    primary: "Summer BBQ",
    secondary: `Who wants to have a cookout this weekend? I just got some furniture
        for my backyard and would love to fire up the grill.`,
    person: "/static/images/avatar/1.jpg",
  },
];

const messages = [
  {
    id: 1,
    text: "Hi, how are you?",
    avatar:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpgByjkKImb-vHcR58pjkOeag3WBJmpD8Fsg&s",
    isOwnMessage: true,
  },
  {
    id: 1,
    text: "Good, and you?",
    avatar:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpgByjkKImb-vHcR58pjkOeag3WBJmpD8Fsg&s",
    isOwnMessage: false,
  },
  {
    id: 1,
    text: "Hi, how are you?",
    avatar:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpgByjkKImb-vHcR58pjkOeag3WBJmpD8Fsg&s",
    isOwnMessage: true,
  },
  {
    id: 1,
    text: "Good, and you?",
    avatar:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpgByjkKImb-vHcR58pjkOeag3WBJmpD8Fsg&s",
    isOwnMessage: false,
  },
  {
    id: 1,
    text: "Hi, how are you?",
    avatar:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpgByjkKImb-vHcR58pjkOeag3WBJmpD8Fsg&s",
    isOwnMessage: true,
  },
  {
    id: 1,
    text: "Good, and you?",
    avatar:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpgByjkKImb-vHcR58pjkOeag3WBJmpD8Fsg&s",
    isOwnMessage: false,
  },
  {
    id: 1,
    text: "Hi, how are you?",
    avatar:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpgByjkKImb-vHcR58pjkOeag3WBJmpD8Fsg&s",
    isOwnMessage: true,
  },
  {
    id: 1,
    text: "Good, and you?",
    avatar:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpgByjkKImb-vHcR58pjkOeag3WBJmpD8Fsg&s",
    isOwnMessage: false,
  },
  {
    id: 1,
    text: "Hi, how are you?",
    avatar:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpgByjkKImb-vHcR58pjkOeag3WBJmpD8Fsg&s",
    isOwnMessage: true,
  },
  {
    id: 1,
    text: "Good, and you?",
    avatar:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpgByjkKImb-vHcR58pjkOeag3WBJmpD8Fsg&s",
    isOwnMessage: false,
  },
  {
    id: 1,
    text: "Hi, how are you?",
    avatar:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpgByjkKImb-vHcR58pjkOeag3WBJmpD8Fsg&s",
    isOwnMessage: true,
  },
  {
    id: 1,
    text: "Good, and you?",
    avatar:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpgByjkKImb-vHcR58pjkOeag3WBJmpD8Fsg&s",
    isOwnMessage: false,
  },
  {
    id: 1,
    text: "Hi, how are you?",
    avatar:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpgByjkKImb-vHcR58pjkOeag3WBJmpD8Fsg&s",
    isOwnMessage: true,
  },
  {
    id: 1,
    text: "Good, and you?",
    avatar:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpgByjkKImb-vHcR58pjkOeag3WBJmpD8Fsg&s",
    isOwnMessage: false,
  },
  {
    id: 1,
    text: "Hi, how are you?",
    avatar:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpgByjkKImb-vHcR58pjkOeag3WBJmpD8Fsg&s",
    isOwnMessage: true,
  },
  {
    id: 1,
    text: "Good, and you?",
    avatar:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpgByjkKImb-vHcR58pjkOeag3WBJmpD8Fsg&s",
    isOwnMessage: false,
  },
  {
    id: 1,
    text: "Hi, how are you?",
    avatar:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpgByjkKImb-vHcR58pjkOeag3WBJmpD8Fsg&s",
    isOwnMessage: true,
  },
  {
    id: 1,
    text: "Good, and you?",
    avatar:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpgByjkKImb-vHcR58pjkOeag3WBJmpD8Fsg&s",
    isOwnMessage: false,
  },
  {
    id: 1,
    text: "Hi, how are you?",
    avatar:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpgByjkKImb-vHcR58pjkOeag3WBJmpD8Fsg&s",
    isOwnMessage: true,
  },
  {
    id: 1,
    text: "Good, and you?",
    avatar:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpgByjkKImb-vHcR58pjkOeag3WBJmpD8Fsg&s",
    isOwnMessage: false,
  },
  {
    id: 1,
    text: "Hi, how are you?",
    avatar:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpgByjkKImb-vHcR58pjkOeag3WBJmpD8Fsg&s",
    isOwnMessage: true,
  },
  {
    id: 1,
    text: "Good, and you?",
    avatar:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpgByjkKImb-vHcR58pjkOeag3WBJmpD8Fsg&s",
    isOwnMessage: false,
  },
  {
    id: 1,
    text: "Hi, how are you?",
    avatar:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpgByjkKImb-vHcR58pjkOeag3WBJmpD8Fsg&s",
    isOwnMessage: true,
  },
  {
    id: 1,
    text: "Good, and you?",
    avatar:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpgByjkKImb-vHcR58pjkOeag3WBJmpD8Fsg&s",
    isOwnMessage: false,
  },
];

export { chats, messages };
